select T1.FOOD_TYPE, T1.REST_ID, T1.REST_NAME, T1.FAVORITES
from REST_INFO T1 JOIN 
  (select FOOD_TYPE, max(FAVORITES) FAVORITES
  from REST_INFO
  group by FOOD_TYPE) T2
where T1.FOOD_TYPE = T2.FOOD_TYPE and T1.FAVORITES = T2.FAVORITES

order by 1 desc