select B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') CREATED_DATE
from USED_GOODS_BOARD B, USED_GOODS_REPLY R
where B.BOARD_ID = R.BOARD_ID and LEFT(B.CREATED_DATE, 7) = '2022-10'
order by R.CREATED_DATE, B.TITLE