with recursive TIME as (
    SELECT 0 as HOUR
    
    union all
    
    SELECT (HOUR + 1) HOUR
    FROM TIME
    WHERE HOUR < 23
),
ANIMAL_COUNT as (
SELECT HOUR(DATETIME) HOUR, COUNT(*) as COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR
    )
    
SELECT TIME.HOUR, ifnull(ANIMAL_COUNT.COUNT, 0) as COUNT
FROM TIME
LEFT JOIN ANIMAL_COUNT
on TIME.HOUR = ANIMAL_COUNT.HOUR
ORDER BY TIME.HOUR