-- 코드를 작성해주세요

SELECT A.ID, B.FISH_NAME, C.LENGTH
FROM FISH_INFO A, FISH_NAME_INFO B, 
    (
    SELECT I.FISH_TYPE, MAX(LENGTH) LENGTH
    FROM FISH_INFO I    
    GROUP BY I.FISH_TYPE    
    ) C    
WHERE A.FISH_TYPE = C.FISH_TYPE and A.LENGTH = C.LENGTH and A.FISH_TYPE = B.FISH_TYPE
ORDER BY A.ID