-- 코드를 작성해주세요
SELECT sum(G.SCORE) as SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL 
FROM HR_DEPARTMENT D, HR_EMPLOYEES E, HR_GRADE G
where D.DEPT_ID = E.DEPT_ID and E.EMP_NO = G.EMP_NO and G.YEAR = 2022
GROUP BY G.EMP_NO
ORDER BY SCORE desc
LIMIT 1