-- SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
-- FROM USED_GOODS_BOARD b join USED_GOODS_REPLY r
-- ON b.BOARD_ID = r.BOARD_ID
-- WHERE LEFT(B.CREATED_DATE, 7) = '2022-10'
-- ORDER BY r.CREATED_DATE, b.TITLE

-- WHERE YEAR(r.CREATED_DATE) = 2022 and MONTH(r.CREATED_DATE) = 10

SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD A
JOIN USED_GOODS_REPLY B
ON A.BOARD_ID = B.BOARD_ID
WHERE YEAR(A.CREATED_DATE) = 2022 AND MONTH(A.CREATED_DATE) = 10
ORDER BY B.CREATED_DATE, A.TITLE