SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD b join USED_GOODS_REPLY r
ON b.BOARD_ID = r.BOARD_ID
-- WHERE YEAR(r.CREATED_DATE) = 2022 and MONTH(r.CREATED_DATE) = 10
where B.BOARD_ID = R.BOARD_ID and LEFT(B.CREATED_DATE, 7) = '2022-10'
ORDER BY r.CREATED_DATE, b.TITLE
